#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, …

#Find the sum of all the even-valued terms in the sequence which do not exceed four million.



prev = 1
curr = 2
even_feb = 2
print(1,end =" ")
print(2,end=" ")
while even_feb<4000000:
    sum = curr + prev
    prev = curr
    curr = sum
    print(sum,end=" ")
    if sum%2 == 0:
        even_feb += sum
print("\nsum =",even_feb)